apiVersion: apps/v1
kind: Deployment
metadata:
  name: intern-app
  labels:
    app: intern-app
spec:
  replicas: 2   # Hafta 4: Yüksek erişilebilirlik (High Availability) ve yük dengeleme için pod sayısını 2'ye çıkardık
  selector:
    matchLabels:
      app: intern-app
  template:
    metadata:
      labels:
        app: intern-app
    spec:
      containers:
        - name: intern-app
          image: ghcr.io/furkanava/devops-train-project:latest  # kendi kullanıcı adını yaz
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: intern-app-config
                  key: APP_ENV   # Hafta 4: APP_ENV değerini merkezi ConfigMap'ten okuyoruz
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health   # Görev (Hafta 2 sonrası): Bunu /health olarak değiştir
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
